package com.haoer.web.entity;

// Generated 2017-9-3 23:13:54 by Hibernate Tools 4.0.0

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private Integer id;
	private String age;
	private String userName;

	public TUser() {
	}

	public TUser(String age, String userName) {
		this.age = age;
		this.userName = userName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
